;Automatic generated by Addon Management
#include *i %A_LineFile%\..\IC_BrivGemFarm_Performance\IC_BrivGemFarm_Component.ahk
#include *i %A_LineFile%\..\IC_BrivGemFarm_Stats\IC_BrivGemFarm_Stats_Component.ahk
#include *i %A_LineFile%\..\IC_GameLocationSettings\IC_GameLocationSettings_Component.ahk
